services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: configs/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  migrate:
    container_name: migrations
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ../migrations/:/migrations
    command: ["-path", "../migrations/", "-database", "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/postgres?sslmode=${DATABASE_SSLMODE}", "up"]

volumes:
  database-data: